// Teams
export const SET_TEAMS = 'SET_TEAMS'
export const SET_CURRENT_TEAM = 'SET_CURRENT_TEAM'

//Groups
export const SET_GROUPS = 'SET_GROUPS'
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP'
export const REMOVE_CURRENT_GROUP = 'REMOVE_CURRENT_GROUP'
export const RESTORE_GROUP = 'RESTORE_GROUP'
